version: "3.5"

services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      PGDATA: /data/postgres
    volumes:
      # - postgres:/data/postgres
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "postgres@example.com"
      PGADMIN_DEFAULT_PASSWORD: secret
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "8080:80"

volumes:
  postgres:
  pgadmin: